ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "brokerType" TEXT DEFAULT 'TINKOFF';
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "bybitApiKey" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "bybitApiSecret" TEXT;
